#!/usr/bin/env python3
"""
repo_ai_detector.py — Phase 2: repo-level AI Classification

Given a whole repository (a local folder, or a public GitHub URL to shallow-clone),
scores every source file for AI-generation "fingerprints" and rolls those up into
one LOC-weighted repo-level score + 4-tier verdict (Green/Human -> Red/AI slop).

This generalizes ai_code_ranker.py (which only scored individual .py files) to:
  - operate on a whole repo, not one file at a time
  - multiple languages, not just Python
  - a public GitHub URL directly (git clone needs no API key/auth for public repos —
    only Phase 1's bulk search/listing of ~10,000 repos needs the GitHub API key)

Usage:
    python3 repo_ai_detector.py <local-path-or-github-url> [--top N] [--json out.json]

Examples:
    python3 repo_ai_detector.py ./debate-arena-main
    python3 repo_ai_detector.py https://github.com/psf/requests --json requests.json
"""

import argparse
import glob
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

# ── Language configuration: extension -> single-line comment prefix ────────
LANGUAGES = {
    '.py': '#', '.rb': '#', '.sh': '#', '.pl': '#',
    '.js': '//', '.jsx': '//', '.ts': '//', '.tsx': '//',
    '.java': '//', '.c': '//', '.h': '//', '.cpp': '//', '.hpp': '//',
    '.cs': '//', '.go': '//', '.rs': '//', '.php': '//',
    '.swift': '//', '.kt': '//',
}

# Vendored/generated/dependency code isn't anyone's original authorship
# (human or AI) — scanning it would just dilute the signal.
SKIP_DIRS = {
    '.git', 'node_modules', 'vendor', 'dist', 'build', 'venv', '.venv',
    '__pycache__', 'target', '.next', '.tox', 'coverage', 'bin', 'obj', 'out',
}

# Block-comment delimiters per language family. Without these, JSDoc blocks and
# Python docstrings get miscounted as *code*, which both hides doc-saturation
# tells and corrupts the comment-to-code ratio.
BLOCK_DELIMS = {
    '#': [('"""', '"""'), ("'''", "'''")],   # Python-family docstrings
    '//': [('/*', '*/')],                    # C-family block comments
}

MAX_FILE_BYTES = 512 * 1024   # skip huge generated/bundled files
WEAK_ONLY_CAP = 40         # ceiling when only ambiguous signals fire (Tier 2 max)
MAX_LINE_CHARS = 1000         # a single 1000+ char line is almost certainly minified

AI_PHRASES = [
    r"here is the (code|implementation|script)",
    r"note: make sure to",
    r"^\s*step 1:",
    r"written by copilot",
    r"generated by (chatgpt|gpt|ai|claude|copilot)",
    r"as an ai( language model)?",
    r"i (cannot|can't) (execute|run) code",
]

# Anchored to the START of the comment: a whole comment that reads "# check if
# the file exists" is a tell; the words "check if" buried mid-sentence in real
# technical prose ("now check if we match one of the registry values") is not.
GENERIC_COMMENT_PATTERNS = [
    r"^\W*(initialize|initialise)\b",
    r"^\W*(function|helper function) to\b",
    r"^\W*check if\b",
    r"^\W*loop (through|over)\b",
    r"^\W*return the\b",
    r"^\W*import required libraries\b",
    r"^\W*(create|define|set up) (a|an|the)\b",
]

# LLMs (Claude especially) love to break code into uniformly-padded section
# banners using box-drawing/em-dash characters most humans never type by hand.
BANNER_COMMENT_RE = re.compile(r"[─━]{3,}")

# ...and often number those banners like a tutorial's steps.
NUMBERED_STEP_RE = re.compile(r"^\W*\d+\.\s+\S")

# Comments that narrate the model's own *editing process* out loud — a trail
# left by an LLM thinking on the page. Deliberately narrow: phrases like
# "we need to", "let's" and "for now" are ordinary human technical writing and
# were removed after they false-positived on pre-LLM code in psf/requests.
META_COMMENTARY_PATTERNS = [
    r"nothing (more|else) to do",
    r"we (replaced|removed|added) (it|that|this|the old)",
    r"actually,? the (original|old|existing)",
    r"we still need .* (above|below|for the|so we)",
    r"so we just\b",
    r"this is the (old|original) \w+ (grid|block|section|node)",
    r"we'?ll (just )?(leave|keep|hide) (it|this|that)",
]

GENERIC_VAR_RE = re.compile(r"\b(data|result|temp|output|item|val|res|response|payload)\b")

# A first-line comment shaped "<file>.<ext> — Description of the file" is an AI
# scaffolding habit. Matched by shape rather than against the real filename, so
# it still fires if the file was later renamed.
FILE_HEADER_RE = re.compile(
    r"^\W{0,4}[\w./-]+\.(py|js|jsx|ts|tsx|java|c|h|cpp|cs|go|rs|rb|php|swift|kt)\s*[—–:-]\s*\S",
    re.IGNORECASE,
)

# Docs that follow an identical template on *every* function — the structural
# signature of generated documentation. Human docs vary: some functions get
# prose, some get nothing, few get a rigid parameter/return skeleton throughout.
DOC_TEMPLATE_RES = [
    re.compile(r"@param\b"), re.compile(r"@returns?\b"),
    re.compile(r"^\s*Args:\s*$", re.MULTILINE), re.compile(r"^\s*Returns:\s*$", re.MULTILINE),
]
PY_DEF_RE = re.compile(r"def\s+\w+\(")
PY_DOCSTRING_RE = re.compile(r'("""|\'\'\')[\s\S]*?\1')
PY_TYPEHINT_DEF_RE = re.compile(r"def\s+\w+\(.*?\)\s*->\s*\w+")
JS_FUNC_RE = re.compile(r"\b(function\s+\w+|const\s+\w+\s*=\s*(async\s*)?\(|\w+\s*\([^)]*\)\s*{)")
JSDOC_RE = re.compile(r"/\*\*[\s\S]*?\*/")


def get_flag_tier(score):
    if score <= 25:
        return "TIER 1 (GREEN)  - Human-Written / Organic"
    elif score <= 50:
        return "TIER 2 (YELLOW) - Low AI Probability"
    elif score <= 75:
        return "TIER 3 (ORANGE) - High AI Probability"
    else:
        return "TIER 4 (RED)    - Likely AI Generated Slop"


def split_comments_and_code(lines, comment_prefix):
    """Attribute each line to comment vs. code, honouring block comments.

    Returns (comment_lines, code_lines) as lists of stripped strings. Block
    comment bodies (JSDoc /** */, Python docstrings) count as comments, not
    code — otherwise doc-heavy AI output looks like dense code.
    """
    delims = BLOCK_DELIMS.get(comment_prefix, [])
    comment_lines, code_lines = [], []
    open_delim = None

    for raw in lines:
        line = raw.strip()
        if not line:
            continue

        if open_delim is not None:
            comment_lines.append(line)
            if open_delim[1] in line:
                open_delim = None
            continue

        if line.startswith(comment_prefix):
            comment_lines.append(line)
            continue

        started = None
        for start, end in delims:
            if line.startswith(start):
                started = (start, end)
                break
        if started:
            comment_lines.append(line)
            # A single-line block (e.g. """docstring""") opens and closes at once.
            rest = line[len(started[0]):]
            if started[1] not in rest:
                open_delim = started
            continue

        code_lines.append(line)

    return comment_lines, code_lines


def analyze_file(filepath):
    ext = os.path.splitext(filepath)[1].lower()
    if ext not in LANGUAGES:
        return None
    try:
        if os.path.getsize(filepath) > MAX_FILE_BYTES:
            return None
        with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
            text = f.read()
    except OSError:
        return None

    lines = text.splitlines()
    if not lines or any(len(l) > MAX_LINE_CHARS for l in lines):
        return None  # empty or looks minified/generated

    comment_prefix = LANGUAGES[ext]
    comment_lines, code_lines = split_comments_and_code(lines, comment_prefix)
    if not code_lines:
        return None

    score = 0
    indicators = []
    # Signals split by specificity. WEAK ones (dense comments, full docstring
    # coverage, generic variable names) are equally the signature of a mature,
    # well-maintained human library — psf/requests trips all of them. They are
    # scored, but on their own they cannot push a file past WEAK_ONLY_CAP into a
    # high-confidence AI tier; that requires at least one AI-specific structural
    # fingerprint (banners, numbered steps, scaffolding header, rigid template,
    # conversational boilerplate).
    strong_signal = False

    # Function count, used by both the doc-template and doc-saturation checks.
    if ext == '.py':
        func_total = len(PY_DEF_RE.findall(text))
    elif ext in ('.js', '.jsx', '.ts', '.tsx'):
        func_total = len(JS_FUNC_RE.findall(text))
    else:
        func_total = 0

    # 1. AI conversational / boilerplate phrases
    for pattern in AI_PHRASES:
        if re.search(pattern, text, re.IGNORECASE | re.MULTILINE):
            score += 30
            strong_signal = True
            indicators.append(f"AI boilerplate phrase match: '{pattern}'")

    # 2. Generic explanatory comments
    generic_hits = sum(
        1 for c in comment_lines
        for pat in GENERIC_COMMENT_PATTERNS
        if re.search(pat, c, re.IGNORECASE)
    )
    if generic_hits >= 3:
        score += 20
        indicators.append(f"High density of generic explanatory comments ({generic_hits})")

    # 2b. Uniform box-drawing section-banner comments (e.g. "// ── Label ────").
    # Scaled by density, not just present/absent — a file with 7-8 of these
    # front-to-back is a much stronger tell than one with 2.
    banner_hits = sum(1 for c in comment_lines if BANNER_COMMENT_RE.search(c))
    if banner_hits >= 2:
        banner_score = min(15 + banner_hits * 5, 40)
        score += banner_score
        strong_signal = True
        indicators.append(f"Uniform Unicode box-drawing section banners ({banner_hits}) — rarely hand-typed by humans")

    # 2c. Sequentially numbered step-comments ("1. ...", "2. ...", ...)
    numbered_hits = sum(1 for c in comment_lines if NUMBERED_STEP_RE.match(c))
    if numbered_hits >= 3:
        numbered_score = min(10 + numbered_hits * 3, 30)
        score += numbered_score
        strong_signal = True
        indicators.append(f"Sequentially numbered step-comments ({numbered_hits}) — tutorial/plan-style AI structuring")

    # 2d. Self-narrating "reasoning trail" comments
    meta_hits = sum(
        1 for c in comment_lines
        for pat in META_COMMENTARY_PATTERNS
        if re.search(pat, c, re.IGNORECASE)
    )
    if meta_hits >= 2:
        meta_score = min(10 + meta_hits * 4, 30)
        score += meta_score
        strong_signal = True
        indicators.append(f"Self-narrating meta-commentary comments ({meta_hits}) — LLM reasoning left in-line")

    # 2e. Self-descriptive file-header comment ("// app.js — does the thing").
    first_comment = next((l for l in lines[:3] if l.strip()), '').strip()
    stripped_header = first_comment.lstrip('#/*! ').strip()
    if FILE_HEADER_RE.match(stripped_header):
        score += 10
        strong_signal = True
        indicators.append("Self-descriptive '<file> — description' header comment (AI scaffolding pattern)")

    # 2f. Uniform doc-template compliance: the same parameter/return skeleton on
    # essentially every function. Distinguishes generated docs from genuinely
    # documented human code, whose docstrings vary in shape and carry context
    # (issue refs, caveats, rationale) rather than restating the signature.
    template_hits = sum(len(rx.findall(text)) for rx in DOC_TEMPLATE_RES)
    if func_total >= 3 and template_hits >= func_total * 1.5:
        score += 15
        strong_signal = True
        indicators.append(
            f"Rigid doc template repeated across all {func_total} functions "
            f"({template_hits} param/return tags) — generated-documentation signature"
        )

    # 3. Comment-to-code ratio
    ratio = len(comment_lines) / len(code_lines)
    if ratio > 0.4:
        score += 15
        indicators.append(f"Unusually high comment-to-code ratio ({ratio:.2f})")

    # 4. Doc-comment / type-hint saturation (language-aware)
    if ext == '.py' and func_total >= 2:
        docstring_count = len(PY_DOCSTRING_RE.findall(text))
        typehint_count = len(PY_TYPEHINT_DEF_RE.findall(text))
        if docstring_count / func_total >= 0.8:
            score += 15
            indicators.append("Near-100% docstring coverage across functions (textbook AI style)")
        if typehint_count / func_total >= 0.8:
            score += 10
            indicators.append("Perfect type-hint saturation across functions")
    elif ext in ('.js', '.jsx', '.ts', '.tsx') and func_total >= 2:
        jsdoc_count = len(JSDOC_RE.findall(text))
        if jsdoc_count / func_total >= 0.8:
            score += 15
            indicators.append("Near-100% JSDoc coverage across functions (textbook AI style)")

    # 5. Generic / repetitive variable names
    generic_vars = GENERIC_VAR_RE.findall(text)
    if len(generic_vars) > 10:
        score += 10
        indicators.append(f"High usage of generic variable names ({len(generic_vars)} occurrences)")

    # Ambiguous evidence alone cannot yield a high-confidence AI verdict.
    if not strong_signal and score > WEAK_ONLY_CAP:
        indicators.append(
            f"(score capped at {WEAK_ONLY_CAP}: only ambiguous documentation-density "
            f"signals fired, no AI-specific structural fingerprint)"
        )
        score = WEAK_ONLY_CAP

    score = min(score, 100)
    return {
        'score': score,
        'tier': get_flag_tier(score),
        'indicators': indicators,
        'loc': len(code_lines),
    }


def collect_files(root):
    files = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS and not d.startswith('.')]
        for fn in filenames:
            if os.path.splitext(fn)[1].lower() in LANGUAGES:
                files.append(os.path.join(dirpath, fn))
    return files


def resolve_target(target):
    """Return (local_dir, is_temp). Clones public GitHub URLs — no API key needed."""
    if target.startswith(('http://', 'https://', 'git@')):
        tmp = tempfile.mkdtemp(prefix='repo_ai_detector_')
        print(f"[*] Cloning {target} (shallow, public repo — no API key needed)...")
        try:
            subprocess.run(
                ['git', 'clone', '--depth', '1', target, tmp],
                check=True, capture_output=True, text=True, errors="replace",
            )
        except subprocess.CalledProcessError as e:
            shutil.rmtree(tmp, ignore_errors=True)
            print(f"[!] git clone failed: {e.stderr.strip()}", file=sys.stderr)
            sys.exit(1)
        return tmp, True
    if not os.path.isdir(target):
        print(f"[!] '{target}' is not a directory and not a recognized git URL.", file=sys.stderr)
        sys.exit(1)
    return target, False


def classify_repo(target, top_n=15, json_out=None):
    root, is_temp = resolve_target(target)
    try:
        files = collect_files(root)
        results = []
        for fp in files:
            r = analyze_file(fp)
            if r:
                r['file'] = os.path.relpath(fp, root)
                results.append(r)

        if not results:
            print(f"[!] No scoreable source files found under '{target}' "
                  f"(supported: {', '.join(sorted(LANGUAGES))}).")
            return

        results.sort(key=lambda r: r['score'], reverse=True)
        total_loc = sum(r['loc'] for r in results)
        weighted_score = sum(r['score'] * r['loc'] for r in results) / total_loc
        repo_tier = get_flag_tier(weighted_score)

        tier_counts = {}
        for r in results:
            tier_counts[r['tier'][:6]] = tier_counts.get(r['tier'][:6], 0) + 1

        print("\n" + "=" * 80)
        print(f" REPO AI-CLASSIFICATION REPORT — {target}")
        print("=" * 80)
        print(f"Files scanned: {len(results)} | Total LOC (approx): {total_loc}")
        print(f"Repo-level AI Score (LOC-weighted): {weighted_score:.1f}/100 -> {repo_tier}")
        print("Tier distribution: " + ", ".join(f"{k}: {v}" for k, v in sorted(tier_counts.items())))

        print(f"\nTop {min(top_n, len(results))} most AI-flagged files:")
        for rank, r in enumerate(results[:top_n], 1):
            print(f"\n  #{rank} {r['file']}  —  {r['score']}/100  {r['tier']}")
            for ind in r['indicators']:
                print(f"      - {ind}")
            if not r['indicators']:
                print("      - No obvious AI patterns detected.")

        if json_out:
            with open(json_out, 'w', encoding='utf-8') as f:
                json.dump({
                    'target': target,
                    'repo_score': round(weighted_score, 2),
                    'repo_tier': repo_tier,
                    'tier_distribution': tier_counts,
                    'files': results,
                }, f, indent=2)
            print(f"\n[*] Full results written to {json_out}")
    finally:
        if is_temp:
            shutil.rmtree(root, ignore_errors=True)


def main():
    parser = argparse.ArgumentParser(description="Classify a repo as human-written vs. AI-generated.")
    parser.add_argument('target', help="Local folder path or public GitHub URL")
    parser.add_argument('--top', type=int, default=15, help="Number of top-flagged files to list (default 15)")
    parser.add_argument('--json', metavar='FILE', help="Write full results to a JSON file")
    args = parser.parse_args()
    classify_repo(args.target, top_n=args.top, json_out=args.json)


if __name__ == "__main__":
    main()
